services:
  # Fitness App Microservices
  authservice:
    image: asgermunk/fitnessapp-authservice:latest
    expose:
      - "8080"
    networks:
      - skibidi

  userservice:
    image: asgermunk/fitnessapp-userservice:latest
    expose:
      - "8080"
    networks:
      - skibidi

  classservice:
    image: asgermunk/fitnessapp-classservice:latest
    expose:
      - "8080"
    networks:
      - skibidi

  socialservice:
    image: asgermunk/fitnessapp-socialservice:latest
    expose:
      - "8080"
    networks:
      - skibidi

  solotrainingservice:
    image: asgermunk/fitnessapp-solotrainingservice:latest
    expose:
      - "8080"
    networks:
      - skibidi

  accesscontrolservice:
    image: asgermunk/fitnessapp-accesscontrolservice:latest
    expose:
      - "8080"
    networks:
      - skibidi

  coachingservice:
    image: asgermunk/fitnessapp-coachingservice:latest
    expose:
      - "8080"
    networks:
      - skibidi

  analyticsservice:
    image: asgermunk/fitnessapp-analyticsservice:latest
    expose:
      - "8080"
    networks:
      - skibidi

  frontend:
    image: asgermunk/fitnessapp-frontend:latest
    expose:
      - "8080"
    networks:
      - skibidi

  # NGINX API Gateway
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - authservice
      - userservice
      - classservice
      - socialservice
      - solotrainingservice
      - accesscontrolservice
      - coachingservice
      - analyticsservice
      - frontend
    ports:
      - "4000:80"
    networks:
      - skibidi

networks:
  skibidi:
    external: true