name: Build and Push Docker Images

on:
  push:
    branches: [ main]


env:
  REGISTRY: docker.io
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        service:
          - name: authservice
            context: .
            dockerfile: ./AuthService/Dockerfile
          - name: userservice
            context: .
            dockerfile: ./UserService/Dockerfile
          - name: classservice
            context: .
            dockerfile: ./ClassService/Dockerfile
          - name: socialservice
            context: .
            dockerfile: ./SocialService/Dockerfile
          - name: solotrainingservice
            context: .
            dockerfile: ./SoloTrainingService/Dockerfile
          - name: accesscontrolservice
            context: .
            dockerfile: ./AccessControlService/Dockerfile
          - name: coachingservice
            context: .
            dockerfile: ./CoachingService/Dockerfile
          - name: analyticsservice
            context: .
            dockerfile: ./AnalyticsService/Dockerfile
          - name: frontend
            context: .
            dockerfile: ./Frontend/Dockerfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service.context }}
          file: ${{ matrix.service.dockerfile }}
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/fitnessapp-${{ matrix.service.name }}:latest
          platforms: linux/amd64,linux/arm64